# Generated by Django 3.2.5 on 2021-07-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_courses_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
